## NUMPY

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

### Crear arreglos
    np.array([])
    .shape
    .type

In [6]:
#crear array (arreglo) de 1 dimension de 5 elementos. np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4,5,6])

print(arr1.shape) #forma de los elementos (cantidad columnas,cantidad filas)
print(arr1.dtype) #tipo de array 
print(arr1) #mostrar el array completo

(6,)
int32
[1 2 3 4 5 6]


### Convertir arreglo en matriz (2 dimensiones)
    .reshape(())

In [7]:
#cambiar el tipo del arreglo a 2 dimensiones (convertirlo en matriz) 2x3, las cantidades deben coincidir sin espacios vacios o dara error
arr2 = arr1.reshape((2,3)) 

print(arr2.shape)
print(arr2.dtype)
print(arr2)

(2, 3)
int32
[[1 2 3]
 [4 5 6]]


### Matriz con numeros aleatorios
    np.random.rand()

In [8]:
#crear array matriz con numeros aleatorios entre 0 y 1
aleatorio4 = np.random.rand(4,4)
print(aleatorio4)

[[0.91261878 0.09950793 0.61138215 0.81385855]
 [0.45745311 0.08755708 0.65905253 0.61224826]
 [0.89363491 0.31151537 0.42121206 0.89973269]
 [0.22918749 0.87615564 0.58001883 0.92470188]]


### Arreglo 2d con listas dentro de listas
    np.array([],[],[])

In [9]:
#crear un arreglo 2d con listas dentro de listas
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d.dtype)
print(arr2d)

int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Crear arreglo de ceros y unos 
    np.zeros(())
    np.ones(())

In [10]:
#crear un arreglo de 0 eligiendo su forma 
ceros3x4 = np.zeros((3,4))
print(ceros3x4,"\n")

#tambien con unos
unos3x4 = np.ones((3,4))
print(unos3x4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Cambiar valor de alguna celda de la matriz
    array[fila_celda,columna_celda] = n

In [11]:
#cambiar el valor de alguna celda del array
unos3x4[2,1] = 10 #primero la fila luego la columna. empieza siempre de 0 
unos3x4

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1., 10.,  1.,  1.]])

### Crear matriz con misma cantidad filas y columnas con 0 y 1
    np.eye(n)

In [12]:
#crear una matriz identidad (misma cantidad filas y columnas)
iguales = np.eye(3)
iguales

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Arreglo en 3d
    np.zero([d1,d2,d3])

In [13]:
#crear un arreglo de 3dimensiones. 
arr3 = np.zeros([2,3,4]) #([cantidad de matices, filas, columnas]) #la cantidad no empieza desde 0
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Transponer filas y columnas
    arr.T

In [14]:
#transponer las filas y columnas de un array
arr5 = np.random.rand(2,4) #2 filas, 4 columnas
arr5.T #4 filas, 2 columnas

array([[0.48596041, 0.36755204],
       [0.14349297, 0.98449552],
       [0.64984265, 0.90839901],
       [0.80465313, 0.44150622]])

### Concatenar arrays horizontal y vertical
    np.hstack([arr1,arr2])
    np.vstack([arr1,arr2])

In [15]:
#concatenar arrays horizontalmente
arr_h = np.hstack([ceros3x4, unos3x4])
print(arr_h,"\n")

#concatenar arrays verticalmente
arr_v = np.vstack([ceros3x4, unos3x4])
print(arr_v)

[[ 0.  0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  1. 10.  1.  1.]] 

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1. 10.  1.  1.]]


### suma total/promedio/mediana/producto/desviacion est/varianza
    np.sum()
    np.mean()
    np.median()
    np.prod()
    np.std()
    np.var()

In [16]:
#calcular la suma de elementos del array
total = np.sum(arr1)
total

#calcular el promedio
promedio = np.mean(arr1)
promedio

#calcular la mediana (valor central)
mitad = np.median(arr1)
mitad

#calcular el producto  (se multiplican todos los elementos)
producto = np.prod(arr1)
producto

#calcular la desviacion estandar (cuanto se desvian los datos de la media en promedio)
desv_est = np.std(arr1)
desv_est

#calcuolar la varianza (cuanto se desvian los datos de la media individualmente)
var = np.var(arr1)
var

2.9166666666666665

### maximo/minimo/ sumas restas
    np.min()
    np.max()

In [17]:
#minimo de los elementos
min = np.min(arr1)
print(min)
#maximo de los elementos
max = np.max(arr1)
max

#sumar, restar, multiplicar etc los ARRAY. deben ser iguales en cantidad de elementos
arr1 + arr1 *arr1 / arr1 - arr1

1


array([1., 2., 3., 4., 5., 6.])

### Crear df a partir de un arreglo 
    pd.DataFrame(arr, columns =["a", "b", "c])
    df.to_numpy()
    df.values

In [18]:
#crear un dataframe a partir de un arreglo numpy
#puedo cambiar el nombre de las columnas con la variable columns=[] esta debe coincidir las variables dentro con la cantidad de columnas que exista
df = pd.DataFrame(arr2d, columns=["A","B","C"])
df

#tambien se puede transformar un data frame en un arreglo de numpy
arr = df.to_numpy()
arr

#con .values hace lo mismo
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Calcular en filas o columnas totales
    np.mean(axis=0)
    np.mean(axis=1)

In [19]:
#calcular estadisticas en las columnas
promc = np.mean(df, axis=0) #promedio
print(promc)

#calcular estadisticas en las filas
promf = np.mean(df, axis=1) #promedio
print(promf)

#con pandas calcular es mas sencillo es solo .mean(axis= 1 o 0)
promcc = df.mean(axis=1)
promcc

A    4.0
B    5.0
C    6.0
dtype: float64
0    2.0
1    5.0
2    8.0
dtype: float64


0    2.0
1    5.0
2    8.0
dtype: float64